### ISSUE TITLE
can we talk?

### ISSUE THREAD

**Issue by McJonnycat** [jigsaw-4277821/VirusR-Psych-Engine-Recreation#1]
### What is your question?

i know we haven't talked in a long time but i didn't know that you were joking. i feel like i know when someone is joking when they put lol in there sentence. i can't just assume that your joking right away. remind you that i haven't know you for so long so idk how you act or how you do things or say things. can we please just talk again. if you don't want to talk to me anymore or not be my friend anymore then its fine i won't text you. but i just wanted to let you know that i didn't know you were joking im sorry dude.

**Comment by jigsaw-4277821** [comment]
Somw people warned me about you that's why I didn't text you but now I only say idk

**Comment by McJonnycat** [comment]
Listen idk what there telling you but I’m not a bad person

**Comment by McJonnycat** [comment]
But who warned you?

**Comment by McJonnycat** [comment]
Cause I whould need a talk with that person
